<?php

namespace App\Http\Requests;

use Illuminate\Validation\Rule;
use Illuminate\Foundation\Http\FormRequest;

class StudentStoreRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules()
    {
        return [
            // Validasi untuk data siswa (sesuaikan dengan field di model Student)
            'nama' => ['required', 'string', 'max:255'],
            'nama_panggilan' => ['nullable', 'string', 'max:100'],
            'nipd' => ['nullable', 'string', 'max:20', Rule::unique('students', 'nipd')->ignore($this->student)],
            'kewarganegaraan' => ['required', 'string', 'max:50'],
            'bahasa_keseharian' => ['nullable', 'string', 'max:50'],
            'jk' => ['required', Rule::in(['L', 'P'])],
            'nisn' => ['nullable', 'string', 'size:10', Rule::unique('students', 'nisn')->ignore($this->student)],
            'tempat_lahir' => ['required', 'string', 'max:100'],
            'tanggal_lahir' => ['required', 'date', 'before:today'],
            'nik' => ['nullable', 'string', 'size:16', Rule::unique('students', 'nik')->ignore($this->student)],
            'alamat' => ['required', 'string', 'max:255'],
            'rt' => ['nullable', 'string', 'max:3'],
            'rw' => ['nullable', 'string', 'max:3'],
            'dusun' => ['nullable', 'string', 'max:100'],
            'kelurahan' => ['nullable', 'string', 'max:100'],
            'kecamatan' => ['nullable', 'string', 'max:100'],
            'kabupaten' => ['nullable', 'string', 'max:100'],
            'provinsi' => ['nullable', 'string', 'max:100'],
            'kode_pos' => ['nullable', 'string', 'max:5'],
            'telepon' => ['nullable', 'string', 'max:15'],
            'hp' => ['nullable', 'string', 'max:15'],
            'email' => ['nullable', 'email', 'max:255', Rule::unique('students', 'email')->ignore($this->student)],
            'skhun' => ['nullable', 'string', 'max:20'],
            'penerima_kps' => ['required', 'boolean'],
            'no_kps' => ['nullable', 'string', 'max:20', 'required_if:penerima_kps,1'],
            'penerima_kip' => ['required', 'boolean'],
            'nomor_kip' => ['nullable', 'string', 'max:20', 'required_if:penerima_kip,1'],
            'nama_di_kip' => ['nullable', 'string', 'max:255', 'required_if:penerima_kip,1'],
            'nomor_kks' => ['nullable', 'string', 'max:20'],
            'no_registrasi_akta' => ['nullable', 'string', 'max:50'],
            'bank' => ['nullable', 'string', 'max:50'],
            'nomor_rekening' => ['nullable', 'string', 'max:50'],
            'rekening_atas_nama' => ['nullable', 'string', 'max:255'],
            'layak_pip' => ['required', 'boolean'],
            'alasan_layak_pip' => ['nullable', 'string', 'max:255', 'required_if:layak_pip,1'],
            'kebutuhan_khusus' => ['nullable', 'string', 'max:255'],
            'anak_ke' => ['nullable', 'integer', 'min:1'],
            'no_kk' => ['nullable', 'string', 'size:16'],
            'jumlah_saudara_kandung' => ['nullable', 'integer', 'min:0'],
            'saudara_tiri' => ['nullable', 'integer', 'min:0'],
            'saudara_angkat' => ['nullable', 'integer', 'min:0'],
            'status_anak' => ['nullable', 'string', 'max:50'],
            'jarak_rumah_km' => ['nullable', 'numeric', 'min:0'],
            'lintang' => ['nullable', 'numeric', 'between:-90,90'],
            'bujur' => ['nullable', 'numeric', 'between:-180,180'],
            'agama_id' => ['required', 'integer', Rule::exists('agama', 'id')],
            'alat_transportasi_id' => ['nullable', 'integer', Rule::exists('alat_transportasi', 'id')],
            'jenis_tinggal_id' => ['nullable', 'integer', Rule::exists('jenis_tinggal', 'id')],
            'riwayat_sekolah_id' => ['nullable', 'integer', Rule::exists('riwayat_sekolah', 'id')],
            // ... lainnya untuk Student

            // Validasi untuk data orang tua
            'ayah_nama' => 'nullable|string|max:255',
            'ayah_tahun_lahir' => 'nullable|digits:4',
            'ayah_pendidikan_id' => 'nullable|exists:pendidikan,id',
            'ayah_pekerjaan_id' => 'nullable|exists:pekerjaan,id',
            'ayah_penghasilan_id' => 'nullable|exists:penghasilan,id',
            'ayah_nik' => 'nullable|string|max:16',
            'ibu_nama' => 'nullable|string|max:255',
            'ibu_tahun_lahir' => 'nullable|digits:4',
            'ibu_pendidikan_id' => 'nullable|exists:pendidikan,id',
            'ibu_pekerjaan_id' => 'nullable|exists:pekerjaan,id',
            'ibu_penghasilan_id' => 'nullable|exists:penghasilan,id',
            'ibu_nik' => 'nullable|string|max:16',
            'wali_nama' => 'nullable|string|max:255',
            'wali_tahun_lahir' => 'nullable|digits:4',
            'wali_pendidikan_id' => 'nullable|exists:pendidikan,id',
            'wali_pekerjaan_id' => 'nullable|exists:pekerjaan,id',
            'wali_penghasilan_id' => 'nullable|exists:penghasilan,id',
            'wali_nik' => 'nullable|string|max:16',

            // Validasi untuk riwayat sekolah
            'jenis_pendaftar' => 'required|in:Siswa Baru,Pindahan,Kembali Bersekolah',
            'sekolah_asal' => 'required_if:jenis_pendaftar,Siswa Baru|nullable|string|max:255',
            'tanggal_ijazah' => 'required_if:jenis_pendaftar,Siswa Baru|nullable|date_format:d-m-Y',
            'nomor_ijazah' => 'nullable|string|max:50',
            'lama_belajar' => 'nullable|numeric|min:0',
            'dari_sekolah' => 'required_if:jenis_pendaftar,Pindahan|nullable|string|max:255',
            'alasan_pindah' => 'required_if:jenis_pendaftar,Pindahan|nullable|string|max:500',
            'catatan_kembali' => 'required_if:jenis_pendaftar,Kembali Bersekolah|nullable|string|max:255',
            'skhun' => 'nullable|string|max:50',
            'kelas_diterima' => 'nullable|string|max:50', // Tambahkan jika ada di form
        ];
    }

    public function messages()
    {
        return [
            'nama.required' => 'Nama lengkap wajib diisi.',
            'nama.string' => 'Nama lengkap harus berupa teks.',
            'nama.max' => 'Nama lengkap tidak boleh lebih dari 255 karakter.',
            'nama_panggilan.string' => 'Nama panggilan harus berupa teks.',
            'nama_panggilan.max' => 'Nama panggilan tidak boleh lebih dari 100 karakter.',
            'nipd.string' => 'NIPD harus berupa teks.',
            'nipd.max' => 'NIPD tidak boleh lebih dari 20 karakter.',
            'nipd.unique' => 'NIPD sudah terdaftar.',
            'kewarganegaraan.required' => 'Kewarganegaraan wajib diisi.',
            'kewarganegaraan.string' => 'Kewarganegaraan harus berupa teks.',
            'kewarganegaraan.max' => 'Kewarganegaraan tidak boleh lebih dari 50 karakter.',
            'bahasa_keseharian.string' => 'Bahasa keseharian harus berupa teks.',
            'bahasa_keseharian.max' => 'Bahasa keseharian tidak boleh lebih dari 50 karakter.',
            'jk.required' => 'Jenis kelamin wajib diisi.',
            'jk.in' => 'Jenis kelamin harus L (Laki-laki) atau P (Perempuan).',
            'nisn.string' => 'NISN harus berupa teks.',
            'nisn.size' => 'NISN harus terdiri dari 10 karakter.',
            'nisn.unique' => 'NISN sudah terdaftar.',
            'tempat_lahir.required' => 'Tempat lahir wajib diisi.',
            'tempat_lahir.string' => 'Tempat lahir harus berupa teks.',
            'tempat_lahir.max' => 'Tempat lahir tidak boleh lebih dari 100 karakter.',
            'tanggal_lahir.required' => 'Tanggal lahir wajib diisi.',
            'tanggal_lahir.date' => 'Tanggal lahir harus dalam format tanggal yang valid.',
            'tanggal_lahir.before' => 'Tanggal lahir harus sebelum hari ini.',
            'nik.string' => 'NIK harus berupa teks.',
            'nik.size' => 'NIK harus terdiri dari 16 karakter.',
            'nik.unique' => 'NIK sudah terdaftar.',
            'alamat.required' => 'Alamat wajib diisi.',
            'alamat.string' => 'Alamat harus berupa teks.',
            'alamat.max' => 'Alamat tidak boleh lebih dari 255 karakter.',
            'rt.string' => 'RT harus berupa teks.',
            'rt.max' => 'RT tidak boleh lebih dari 3 karakter.',
            'rw.string' => 'RW harus berupa teks.',
            'rw.max' => 'RW tidak boleh lebih dari 3 karakter.',
            'dusun.string' => 'Dusun harus berupa teks.',
            'dusun.max' => 'Dusun tidak boleh lebih dari 100 karakter.',
            'kelurahan.string' => 'Kelurahan harus berupa teks.',
            'kelurahan.max' => 'Kelurahan tidak boleh lebih dari 100 karakter.',
            'kecamatan.string' => 'Kecamatan harus berupa teks.',
            'kecamatan.max' => 'Kecamatan tidak boleh lebih dari 100 karakter.',
            'kabupaten.string' => 'Kabupaten harus berupa teks.',
            'kabupaten.max' => 'Kabupaten tidak boleh lebih dari 100 karakter.',
            'provinsi.string' => 'Provinsi harus berupa teks.',
            'provinsi.max' => 'Provinsi tidak boleh lebih dari 100 karakter.',
            'kode_pos.string' => 'Kode pos harus berupa teks.',
            'kode_pos.max' => 'Kode pos tidak boleh lebih dari 5 karakter.',
            'telepon.string' => 'Telepon harus berupa teks.',
            'telepon.max' => 'Telepon tidak boleh lebih dari 15 karakter.',
            'hp.string' => 'HP harus berupa teks.',
            'hp.max' => 'HP tidak boleh lebih dari 15 karakter.',
            'email.email' => 'Email harus dalam format yang valid.',
            'email.max' => 'Email tidak boleh lebih dari 255 karakter.',
            'email.unique' => 'Email sudah terdaftar.',
            'skhun.string' => 'SKHUN harus berupa teks.',
            'skhun.max' => 'SKHUN tidak boleh lebih dari 20 karakter.',
            'penerima_kps.required' => 'Status penerima KPS wajib diisi.',
            'penerima_kps.boolean' => 'Status penerima KPS harus Ya atau Tidak.',
            'no_kps.string' => 'Nomor KPS harus berupa teks.',
            'no_kps.max' => 'Nomor KPS tidak boleh lebih dari 20 karakter.',
            'no_kps.required_if' => 'Nomor KPS wajib diisi jika penerima KPS adalah Ya.',
            'penerima_kip.required' => 'Status penerima KIP wajib diisi.',
            'penerima_kip.boolean' => 'Status penerima KIP harus Ya atau Tidak.',
            'nomor_kip.string' => 'Nomor KIP harus berupa teks.',
            'nomor_kip.max' => 'Nomor KIP tidak boleh lebih dari 20 karakter.',
            'nomor_kip.required_if' => 'Nomor KIP wajib diisi jika penerima KIP adalah Ya.',
            'nama_di_kip.string' => 'Nama di KIP harus berupa teks.',
            'nama_di_kip.max' => 'Nama di KIP tidak boleh lebih dari 255 karakter.',
            'nama_di_kip.required_if' => 'Nama di KIP wajib diisi jika penerima KIP adalah Ya.',
            'nomor_kks.string' => 'Nomor KKS harus berupa teks.',
            'nomor_kks.max' => 'Nomor KKS tidak boleh lebih dari 20 karakter.',
            'no_registrasi_akta.string' => 'Nomor registrasi akta harus berupa teks.',
            'no_registrasi_akta.max' => 'Nomor registrasi akta tidak boleh lebih dari 50 karakter.',
            'bank.string' => 'Nama bank harus berupa teks.',
            'bank.max' => 'Nama bank tidak boleh lebih dari 50 karakter.',
            'nomor_rekening.string' => 'Nomor rekening harus berupa teks.',
            'nomor_rekening.max' => 'Nomor rekening tidak boleh lebih dari 50 karakter.',
            'rekening_atas_nama.string' => 'Rekening atas nama harus berupa teks.',
            'rekening_atas_nama.max' => 'Rekening atas nama tidak boleh lebih dari 255 karakter.',
            'layak_pip.required' => 'Status layak PIP wajib diisi.',
            'layak_pip.boolean' => 'Status layak PIP harus Ya atau Tidak.',
            'alasan_layak_pip.string' => 'Alasan layak PIP harus berupa teks.',
            'alasan_layak_pip.max' => 'Alasan layak PIP tidak boleh lebih dari 255 karakter.',
            'alasan_layak_pip.required_if' => 'Alasan layak PIP wajib diisi jika layak PIP adalah Ya.',
            'kebutuhan_khusus.string' => 'Kebutuhan khusus harus berupa teks.',
            'kebutuhan_khusus.max' => 'Kebutuhan khusus tidak boleh lebih dari 255 karakter.',
            'anak_ke.integer' => 'Anak ke harus berupa angka.',
            'anak_ke.min' => 'Anak ke harus minimal 1.',
            'no_kk.string' => 'Nomor KK harus berupa teks.',
            'no_kk.size' => 'Nomor KK harus terdiri dari 16 karakter.',
            'jumlah_saudara_kandung.integer' => 'Jumlah saudara kandung harus berupa angka.',
            'jumlah_saudara_kandung.min' => 'Jumlah saudara kandung tidak boleh kurang dari 0.',
            'saudara_tiri.integer' => 'Jumlah saudara tiri harus berupa angka.',
            'saudara_tiri.min' => 'Jumlah saudara tiri tidak boleh kurang dari 0.',
            'saudara_angkat.integer' => 'Jumlah saudara angkat harus berupa angka.',
            'saudara_angkat.min' => 'Jumlah saudara angkat tidak boleh kurang dari 0.',
            'status_anak.string' => 'Status anak harus berupa teks.',
            'status_anak.max' => 'Status anak tidak boleh lebih dari 50 karakter.',
            'jarak_rumah_km.numeric' => 'Jarak rumah harus berupa angka.',
            'jarak_rumah_km.min' => 'Jarak rumah tidak boleh kurang dari 0.',
            'lintang.numeric' => 'Lintang harus berupa angka.',
            'lintang.between' => 'Lintang harus antara -90 dan 90 derajat.',
            'bujur.numeric' => 'Bujur harus berupa angka.',
            'bujur.between' => 'Bujur harus antara -180 dan 180 derajat.',
            'agama_id.required' => 'Agama wajib diisi.',
            'agama_id.integer' => 'Agama harus berupa ID yang valid.',
            'agama_id.exists' => 'Agama yang dipilih tidak valid.',
            'alat_transportasi_id.integer' => 'Alat transportasi harus berupa ID yang valid.',
            'alat_transportasi_id.exists' => 'Alat transportasi yang dipilih tidak valid.',
            'jenis_tinggal_id.integer' => 'Jenis tinggal harus berupa ID yang valid.',
            'jenis_tinggal_id.exists' => 'Jenis tinggal yang dipilih tidak valid.',
            'riwayat_sekolah_id.integer' => 'Riwayat sekolah harus berupa ID yang valid.',
            'riwayat_sekolah_id.exists' => 'Riwayat sekolah yang dipilih tidak valid.',
        ];
    }
}
